"""
Insert words data into Supabase "words" table
"""
from supabase_test import supabase_admin

WORDS_DATA = [
    {
        "active": True,
        "vocabulary": "abacus",
        "explanation": "算盘",
        "etymology": "来自希腊语 abax（板、计算板）",
        "reasoning": "abax（计算板）→ 古代在沙板/木板上计算 → 演变为带珠子的计算工具",
        "memory_tips": '联想"阿伯酷似"算盘高手：画面里阿伯(aba)酷似(cus)打算盘的老掌柜',
        "example": "She used an abacus to teach the children basic arithmetic.",
        "translation": "她用算盘教孩子们基础算术。",
        "source": "basic, wordgod_c01_007",
        "note": "",
    },
    {
        "active": True,
        "vocabulary": "abandon",
        "explanation": "放弃，遗弃",
        "etymology": "a-（远离）, ban（禁止）, -don（给予）",
        "reasoning": "a(远离) + ban(禁止) + don(给予) → 远离并禁止给予 → 放弃、遗弃",
        "memory_tips": '想象一个"阿班"(a-ban)同学"咚"(don)地扔掉书包，放弃考试的场景',
        "example": "She had to abandon her car in the snowstorm.",
        "translation": "她不得不在暴风雪中弃车而走。",
        "source": "basic, wordgod_c01_008",
        "note": "",
    },
    {
        "active": True,
        "vocabulary": "abashed",
        "explanation": "尴尬的，窘迫的",
        "etymology": "a-（加强）, bash（羞愧）",
        "reasoning": "a(加强) + bash(羞愧) → 强调羞愧感 → 感到尴尬/窘迫",
        "memory_tips": '联想"啊！巴士(bash)上出丑了"的尴尬场景，脸红的画面',
        "example": "She felt abashed when she realized her dress was on inside out.",
        "translation": "当她发现自己的衣服穿反了时，感到非常尴尬。",
        "source": "basic, wordgod_c01_020",
        "note": "",
    },
    {
        "active": True,
        "vocabulary": "abate",
        "explanation": "减轻，减弱",
        "etymology": "a-（表示方向）, bat（击打）",
        "reasoning": "a-(向) + bat(击打) → 向击打的方向减弱 → 减轻/减弱",
        "memory_tips": "想象蝙蝠(bat)飞走(a-way)后，噪音逐渐减弱",
        "example": "The storm began to abate after midnight.",
        "translation": "午夜过后，暴风雨开始减弱了。",
        "source": "basic, wordgod_c01_022",
        "note": "",
    },
    {
        "active": True,
        "vocabulary": "abbreviate",
        "explanation": "缩写，缩短",
        "etymology": "ab-（加强）, brevi（短）, -ate（使成为）",
        "reasoning": "ab(加强) + brevi(短) + ate(使成为) → 使变得更短 → 缩写",
        "memory_tips": "想象把长单词\"剪短\"（brev-像\"剪\"的动作），变成缩写形式，就像把\"中华人民共和国\"缩写成\"中国\"",
        "example": "Please abbreviate the word \"abbreviation\" to \"abbr.\" for this document.",
        "translation": "请将单词\"abbreviation\"在这份文档中缩写为\"abbr.\"。",
        "source": "basic, wordgod_c01_023",
        "note": "",
    },
    {
        "active": True,
        "vocabulary": "abdicate",
        "explanation": "放弃（王位、权力或责任）",
        "etymology": "ab-（离开）, dic（说）, -ate（动词后缀）",
        "reasoning": "ab(离开) + dic(说) + ate(动词) → 通过宣布离开 → 放弃权力",
        "memory_tips": "想象国王\"阿伯\"(ab)对着话筒(dic)宣布\"我退位啦！\"(ate)，然后离开王座",
        "example": "King Edward VIII abdicated the throne in 1936 to marry Wallis Simpson.",
        "translation": "爱德华八世于1936年退位，以便与华里丝·辛普森结婚。",
        "source": "basic, wordgod_c01_024",
        "note": "",
    },
    {
        "active": True,
        "vocabulary": "abdomen",
        "explanation": "腹部，肚子",
        "etymology": "abdo（隐藏）, men（身体部位）",
        "reasoning": "abdo(隐藏) + men(身体部位) → 被隐藏的身体部位 → 腹部",
        "memory_tips": "想象腹部是\"ab-躲-men门\"后面藏着的部位，就像躲在门后的啤酒肚",
        "example": "She felt a sharp pain in her lower abdomen after the workout.",
        "translation": "锻炼后她感到下腹部一阵剧痛。",
        "source": "basic, wordgod_c01_037",
        "note": "",
    },
    {
        "active": True,
        "vocabulary": "abduct",
        "explanation": "绑架，劫持",
        "etymology": "ab（离开）, duct（引导）",
        "reasoning": "ab(离开) + duct(引导) → 引导某人离开 → 强行带走 → 绑架",
        "memory_tips": "想象一个\"阿布大叔(ab-duct)\"用导管(duct)把人吸走绑架的场景",
        "example": "The criminals planned to abduct the CEO's daughter for ransom.",
        "translation": "犯罪分子计划绑架CEO的女儿以索取赎金。",
        "source": "basic, wordgod_c01_043",
        "note": "",
    },
    {
        "active": True,
        "vocabulary": "abed",
        "explanation": "在床上",
        "etymology": "a-（在...状态中）, bed（床）",
        "reasoning": "a-(在...中) + bed(床) → 处于床上的状态 → 在床上",
        "memory_tips": "想象字母\"A\"躺在\"bed\"上睡大觉，画面感十足",
        "example": "She was still abed when the phone rang at 8 a.m.",
        "translation": "早上8点电话响起时，她还躺在床上睡觉",
        "source": "basic, wordgod_c01_044",
        "note": "",
    },
    {
        "active": True,
        "vocabulary": "aberrant",
        "explanation": "异常的，偏离常规的",
        "etymology": "ab（偏离）, err（漫游，走）, -ant（形容词后缀）",
        "reasoning": "ab(偏离) + err(走) + ant(形容词后缀) → 偏离正常路线的行走 → 异常的",
        "memory_tips": "想象一只蚂蚁(ant)偏离(ab)了蚁群路线，在错误(err)的地方游荡 → 这就是\"异常行为\"！",
        "example": "His aberrant behavior at the meeting surprised everyone.",
        "translation": "他在会议上的异常行为让所有人都感到惊讶。",
        "source": "basic, wordgod_c01_045",
        "note": "",
    },
]

if __name__ == "__main__":
    try:
        response = supabase_admin.table("words").insert(WORDS_DATA).execute()
        print(f"OK - Inserted {len(WORDS_DATA)} rows into words table")
    except Exception as e:
        print(f"FAIL - Insert error: {e}")
